  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  headTilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: headTilt
    pid: {p: 3.0, i: 1.0, d: 0.05}
  headPan_position_controller:
    type: effort_controllers/JointPositionController
    joint: headPan
    pid: {p: 3.0, i: 1.0, d: 0.05}
  mouth_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mouth_joint
    pid: {p: 3.0, i: 1.0, d: 0.05}
  neck_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: neck_joint
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRF1_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRF1
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLF1_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLF1
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRF2_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRF2
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLF2_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLF2
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRF3_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRF3
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLF3_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLF3
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRB1_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRB1
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLB1_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLB1
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRB2_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRB2
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLB2_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLB2
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legRB3_position_controller:
    type: effort_controllers/JointPositionController
    joint: legRB3
    pid: {p: 3.0, i: 1.0, d: 0.05}
  legLB3_position_controller:
    type: effort_controllers/JointPositionController
    joint: legLB3
    pid: {p: 3.0, i: 1.0, d: 0.05}
  tailPan_position_controller:
    type: effort_controllers/JointPositionController
    joint: tailPan
    pid: {p: 0.1, i: 0.0, d: 0.0}
  tailTilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: tailTilt
    pid: {p: 0.1, i: 0.0, d: 0.0}
  R_ear_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_ear_tilt
    pid: {p: 1.0, i: 0.0, d: 1.0}
  R_ear_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_ear_joint
    pid: {p: 1.0, i: 0.0, d: 1.0}
  L_ear_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_ear_tilt
    pid: {p: 1.0, i: 0.0, d: 1.0}
  L_ear_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_ear_joint
    pid: {p: 1.0, i: 0.0, d: 1.0}
